baseURL = "https://darrencohen.me/"
languageCode = "en-us"
title = "Darren Cohen"
paginate = 25

[outputs]
home = ["HTML", "RSS"]
section = ["HTML", "RSS"]

[params]
subtitle = "Links Iâ€™m reading, with short notes."
